rng.event_type.*.*.third_party.rng_conflict:
  type: mapping
  mapping:
    conflicts:
      type: sequence
      sequence:
        type: rng_conflict.conflict_set

rng_conflict.conflict_set:
  type: sequence
  sequence:
    type: rng_conflict.field

rng_conflict.field:
  type: mapping
  mapping:
    field_name:
      type: string
